-- Reset stuck ingestion rows + bulk-acknowledge stale alerts
-- Context: the ingest-orchestrator was hitting the 150s Supabase wall-clock
-- timeout on every pg_cron tick because the Docling fetch had no AbortController.
-- The watchdog (stuck_ingestion_recovery) kept resetting processing->pending,
-- causing an infinite retry loop.  This migration clears the backlog so the
-- patched orchestrator (fix/ingest-pdf-abort-timeout) can start cleanly.

-- 1. Reset any row currently stuck in 'processing' back to 'pending'.
--    The orchestrator now returns before the wall-clock limit, so these rows
--    will be retried and the watchdog should not need to auto-reset them again.
UPDATE public.pending_ingestions
  SET
    status          = 'pending',
    last_error      = 'manual reset: was stuck in processing',
    next_attempt_at = NOW() + interval '5 minutes',
    updated_at      = NOW()
  WHERE status = 'processing';

-- 2. Skip Board Package PDFs that Docling consistently HTTP 500s on.
--    These have 20+ attempts with Docling HTTP 500 errors -- they are too
--    large for the free-tier HF Spaces instance.
UPDATE public.pending_ingestions
  SET
    status     = 'skipped',
    last_error = 'skipped: Docling HTTP 500 after 20+ attempts (Board Package too large for free HF Spaces)',
    updated_at = NOW()
  WHERE status = 'failed'
    AND attempts >= 20;

-- 3. Stagger next_attempt_at for remaining pending rows so they do not all
--    fire simultaneously on the next pg_cron tick.
UPDATE public.pending_ingestions
  SET
    next_attempt_at = NOW() + (CASE
      WHEN attempts < 15 THEN interval '5 minutes'
      WHEN attempts < 35 THEN interval '10 minutes'
      ELSE interval '15 minutes'
    END),
    updated_at = NOW()
  WHERE status = 'pending'
    AND (next_attempt_at IS NULL OR next_attempt_at <= NOW() + interval '1 minute');

-- 4. Bulk-acknowledge all outstanding pending_alerts to clear the noise backlog
--    generated by the watchdog cycle.
UPDATE public.pending_alerts
  SET
    acknowledged    = true,
    acknowledged_at = NOW()
  WHERE acknowledged = false;
